### ISSUE TITLE
Corrupted PAM after packing it

### ISSUE THREAD

**Issue by Bobotka** [Haruma-VN/Sen#21]
Unpacking the PAM with Sen works fine, but packing it back with Sen corrupts it.
After packing the PAM, I tried unpacking it and see if everything works but Adobe Animate couldn't load due to memory issues and that the file might be corrupted.

I tried with 2i and 2c PAMs, same result.
I tried unpacking and packing back without editing anything, same result.
I tried editing different zombies, same result.

**Comment by harumazzz** [comment]
Can you provide some sample files?

**Comment by harumazzz** [comment]
The memory issues you occur because of the pam is too large, or your pc memory is too low, not tool issue. I don't know the broken part you mention is in which version but I or many people have not occurred your situation, can you record a video on what you did so I can try to help?

**Comment by Bobotka** [comment]
https://youtu.be/JXrGeiSXH6E

Let me know If I should specify something in the video

**Comment by harumazzz** [comment]
Sorry that I response lately, can you install version 2.1 (newest) and then test again? If still occur can you send me the pam and media folder? thanks again

**Comment by Bobotka** [comment]
Don't worry, I'm not in a hurry

Either ways I tried installing 2.1 version and try again. It seems nothing has changed.

Here are the files: https://mega.nz/folder/bgI3UayI#qsTM5KDLToLE6b99JVAGAA
in "original" folder is the original .PAM and the media sprites
in "modified" folder is the modified packed .PAM and the unpacked form of it.

**Comment by harumazzz** [comment]
This issue has been fixed in: https://github.com/Haruma-VN/Sen/commit/1fc34cf0f7fefd7a8b3582420098bbd25b064918
Please wait for the next version and retry, after that if it solved your problem please close this issue later.

**Comment by harumazzz** [comment]
In the newest ver the pam function has been updated please try again.

**Comment by harumazzz** [comment]
If you still occur please reopen this issue. If you don't respond I will mark this issue as completed.

**Comment by Bobotka** [comment]
Really sorry for the very late response.

I tried with the new version of Sen, and the same issues still occur. The same error in the "Output" tab appears when trying to check in Adobe Animate. I tried it with the same files that I provided in this issue, and I retried with different and new files as well.

Let me know If I should provide any further information

Edit: Perhaps I should try with a different version of Adobe Animate? I'm currently using a 2023 version of it.

**Comment by harumazzz** [comment]
Maybe replace the machine current behavior, some countries use comma instead of dot, this causes many issues to adobe because it treats differently. Please try this and tell me the issue later.

**Comment by Bobotka** [comment]
I'm not sure what do you mean by "machine current behavior" although i understand what you mean by the description. Is that an option related to the Adobe Animate software itself or is it related to my device? Can't seem to find information about it either. Sorry since i'm not too deep into those stuff.

**Comment by harumazzz** [comment]
Open and find this in Control Panel. Then you replace Decimal Symbols from comma to dot.
![image](https://github.com/Haruma-VN/Sen/assets/114157573/4e68c314-a5da-43af-aa3e-1b14a60de790)

**Comment by Bobotka** [comment]
That solved the issue, thanks a lot for the help!
